In [6]:
import numpy as np
import matplotlib.pyplot as plt

### Prepare synthetic data

In [ ]:
X = np.random.rand(2, 8003)
y = np.array(([1], [0]))

In [8]:
X

array([[0.93762872, 0.18428061, 0.96320183, ..., 0.99336021, 0.56358254,
        0.59320801],
       [0.68251548, 0.38104318, 0.39455955, ..., 0.9862014 , 0.2347307 ,
        0.88605835]], shape=(2, 8003))

In [ ]:
print(y)
print(y.shape)

[[1]
 [0]]
(2, 1)


### Linear model

In [20]:
X_bias = np.c_[np.ones(X.shape[0]), X]

In [24]:
print(X_bias[:])

[[1.         0.93762872 0.18428061 ... 0.99336021 0.56358254 0.59320801]
 [1.         0.68251548 0.38104318 ... 0.9862014  0.2347307  0.88605835]]


In [29]:
num_params = len(X_bias[0])
print(num_params)

8004


In [ ]:
theta = np.random.rand(num_params, 1) * 0.01
print(theta.shape)

(8004, 1)


In [ ]:
def predict(X, theta):
    return X.dot(theta)

def compute_loss(y, y_hat):
    N = y.shape[0]
    return np.sum((y - y_hat) ** 2) / N

def compute_gradient(y_hat, y, X):
    N = y.shape[0]
    k = 2 * (y_hat - y)

    return X.T.dot(k) / N

def update_gradient (theta, grad, lr = 0.001):
    theta = theta - lr * grad
    return theta

pred = predict(X_bias, theta)
loss = compute_loss(y, pred)
grad = compute_gradient(pred, y, X_bias)



print(pred)
print(loss)
print(grad)
print(f"Previous theta: {theta[:5]}")
new_theta = update_gradient(theta, grad)
print(f"New theta: {new_theta}")

[[1983.97284577]
 [1998.12567983]]
3962343.7697180565
[[3981.09852559]
 [3223.04400057]
 [1126.79562339]
 ...
 [3940.36067519]
 [1586.5903126 ]
 [2946.77130573]]
Previous theta: [[0.40261457]
 [0.3030827 ]
 [0.22135321]
 [0.32836018]
 [0.63047989]]
New theta: [[-3.57848395]
 [-2.9199613 ]
 [-0.90544241]
 ...
 [-3.04284595]
 [-0.8058875 ]
 [-2.50058933]]


### Logistic

In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def predict(X, theta):
    z = X.dot(theta)
    return sigmoid(z)

def predict_classes(y_hat, threshold=0.5):
    return (y_hat >= threshold).astype(int)

def compute_loss(y, y_hat):
    N = y.shape[0]

    loss = -1/N * np.sum(y * np.log(y_hat + 1e-15) + (1 - y) * np.log(1 - y_hat + 1e-15))
    return loss

def compute_gradient(y_hat, y, X):
    N = y.shape[0]
    # (8004, 2) dot (2, 1) -> (8004, 1)
    return X.T.dot(y_hat - y) / N

def update_gradient(theta, grad, lr=0.1):
    return theta - lr * grad

In [ ]:
y_hat = predict(X_bias, theta)
loss = compute_loss(y, y_hat)
grad = compute_gradient(y_hat, Y, X_bias)
theta = update_gradient(theta, grad)

print(loss)
print(y_hat.shape)

17.269388197455342
(2, 1)


Training

In [ ]:
epoch_max = 2
lr = 0.001 
N = len(y)
losses = []

for epoch in range(epoch_max):
    y_hat = predict(X_bias, theta)
    loss = compute_loss(y, y_hat) 
    losses.append(loss)

    gradient = compute_gradient(y_hat, y, X_bias)
    theta = update_gradient(theta, gradient, lr)
    print(f'Epoch {epoch+1}: Loss = {loss:.6f}, theta (5 pts) = {theta.flatten()[:5]}')

final_theta = theta
print(final_theta)

Epoch 1: Loss = 17.269388, theta (5 pts) = [0.35211457 0.26861567 0.20211053 0.30843492 0.62632091]
Epoch 2: Loss = 17.269388, theta (5 pts) = [0.35161457 0.26827441 0.20192001 0.30823764 0.62627974]
[[0.35161457]
 [0.26827441]
 [0.20192001]
 ...
 [0.84721845]
 [0.76873155]
 [0.400993  ]]
