In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv("../data/processed_spam.csv")

In [4]:
documents = dataset['processed_text'].tolist()
documents[:5]

['go jurong point crazy available on bugi n great world la e buffet cine there got amore wat',
 'ok lar jok wif u oni',
 'free entry <NUM> wk comp win fa cup final tkt <NUM>st may <NUM> text fa <NUM> receive entry questionstd txt ratetc app <NUM>over<NUM>',
 'u dun say so ear hor u c already then say',
 'nah dont think goe usf liv around here though']

### Build Vocabulary

In [5]:
vocab = {}
for doc in documents:
    doc = str(doc)
    words = doc.split()
    for word in words:
        if word not in vocab:
            vocab[word] = len(vocab)

print(len(vocab))

8003


In [6]:
num_docs = len(documents)
vocab_size = len(vocab)

### Bag Of Word

In [7]:
bow_matrix = np.zeros((num_docs, vocab_size), dtype=int)

In [8]:
for i, doc in enumerate(documents):
    doc = str(doc)
    for word in doc.split():
        if word in vocab:
            word_index = vocab[word]
            bow_matrix[i, word_index] += 1

In [9]:
print(bow_matrix[:2])

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### TF-IDF

In [12]:
df = np.sum(bow_matrix > 0, axis = 0)
print(df[:10])

[416   1  33  14  16 202   7 118 105  34]


In [14]:
idf_vector = np.log((1 + num_docs) / (1 + df)) + 1
print(idf_vector[:10])

[3.59260257 8.93254161 6.09932826 6.91763859 6.79247544 4.31248281
 7.54624725 4.84656529 4.96224969 6.07034073]


In [15]:
tfidf_matrix = bow_matrix * idf_vector
print(np.round(tfidf_matrix[0], 2))

[3.59 8.93 6.1  ... 0.   0.   0.  ]


In [16]:
print(tfidf_matrix.shape)

(5572, 8003)
